name: InstructoHub
description: A learning platform.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4


  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4

  # For making API calls
  http: ^1.1.0 
  # For persisting the auth token
  shared_preferences: ^2.2.2
  # For rendering SVG images
  flutter_svg: ^2.0.7
  
  cupertino_icons: ^1.0.2
  gh_pages: ^0.1.1

  flutter_html: ^3.0.0-beta.2 

  
  dio: ^5.1.1

  path_provider: ^2.1.3
  open_filex: ^4.4.0
  file_picker: ^8.0.3 
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  emoji_picker_flutter: ^2.2.0
  intl: ^0.19.0 
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # Check pub.dev for the latest version

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon" # can be true or a string to name the icon
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # optional: ensures adaptive icons are generated

